##################################
#   ParamountLib Main Config
#   Made by ParamountDev
#   TG-Link: @paramount1_dev
##################################

# Do not change this value.
author: "ParamountDev"
